In [1]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.2/242.2 KB 1.9 MB/s eta 0:00:00a 0:00:01
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.9

In [2]:
from openpyxl import load_workbook 
wb = load_workbook(filename = '/home/jovyan/work/Downloads/PH-KPI-KIN04-IVB-TRM-4397 SKMEL30 HMVII 2D 7day CTG Combo_Report-20210915.xlsx')

/opt/conda/lib/python3.9/site-packages/openpyxl/reader/drawings.py:59: UserWarning: wmf image format is not supported so the image is being dropped
  warn(msg)

In [3]:
sheet_ranges = wb['SK-MEL-30']
print(sheet_ranges['D18'].value)

4460

In [1]:
import pandas as pd
import numpy as np
from io import StringIO

In [2]:
rdata = StringIO("""
2	3	4	5	6	7	8	9	10	11
980	1060	830	1320	1950	2560	2300	2430	2100	1520
479280	33900	83910	263530	491050	531310	579080	574590	521740	429980
68380	17140	20420	25360	33550	52890	56630	60620	49200	37980
161810	19410	30940	52950	124610	188660	212050	325810	154590	144730
380860	22970	46150	132940	317210	727110	508000	476700	399040	397120
497370	31090	86230	279370	763610	582590	608670	530260	588880	519750
670760	35850	131990	314220	648450	734670	634830	680710	612700	676520
"""
)

In [2]:
rdata = StringIO("""2	3	4	5	6	7	8	9	10	11
2420	1920	1700	3250	4260	5170	5560	4990	5040	4260
1686060	82660	250510	1032750	1647830	1786380	1761850	1670490	1751530	1660900
202320	25120	36190	51050	70460	119120	206770	327480	292810	267980
1043080	46800	71110	132760	266650	634650	1145250	1393830	1416630	1228810
1849450	67590	134990	335370	1156640	1858480	1948550	1990390	1961480	1933870
2051630	83230	229830	776590	1721250	2088860	2136380	2112720	2134130	2118100
1962220	90970	255120	1063600	1926220	2237460	2163090	2174650	2188160	2198830""")

In [3]:
dfo = pd.read_csv(rdata, delim_whitespace=True)
dfo

,2,3,4,5,6,7,8,9,10,11
0,980,1060,830,1320,1950,2560,2300,2430,2100,1520
1,479280,33900,83910,263530,491050,531310,579080,574590,521740,429980
2,68380,17140,20420,25360,33550,52890,56630,60620,49200,37980
3,161810,19410,30940,52950,124610,188660,212050,325810,154590,144730
4,380860,22970,46150,132940,317210,727110,508000,476700,399040,397120
5,497370,31090,86230,279370,763610,582590,608670,530260,588880,519750
6,670760,35850,131990,314220,648450,734670,634830,680710,612700,676520

In [4]:
dfo = dfo.loc[1:, :]
dfo.reset_index(inplace=True, drop=True)

In [5]:
dfo

,2,3,4,5,6,7,8,9,10,11
0,479280,33900,83910,263530,491050,531310,579080,574590,521740,429980
1,68380,17140,20420,25360,33550,52890,56630,60620,49200,37980
2,161810,19410,30940,52950,124610,188660,212050,325810,154590,144730
3,380860,22970,46150,132940,317210,727110,508000,476700,399040,397120
4,497370,31090,86230,279370,763610,582590,608670,530260,588880,519750
5,670760,35850,131990,314220,648450,734670,634830,680710,612700,676520

In [49]:
# do log division
dl = pd.DataFrame(data={"vals": [10, 3, 2]})
dl = dl.assign(logged=lambda x: np.log(x.vals))
dl.loc[1:,"logged"] *= -1
dl["logs_cummulated"] = dl.logged.cumsum()
dl["cumdiv"] = np.exp(dl.logs_cummulated)

In [50]:
dl

   vals    logged  logs_cummulated     cumdiv
0    10  2.302585         2.302585  10.000000
1     3 -1.098612         1.203973   3.333333
2     2 -0.693147         0.510826   1.666667

In [6]:
start_nbr = 1000.0
horiz_conc = [0.0]
for i in range(9):
    horiz_conc.append(start_nbr)
    start_nbr /= 3.0

In [6]:
horiz_conc

[0.0,
 1000.0,
 333.3333333333333,
 111.1111111111111,
 37.03703703703703,
 12.345679012345677,
 4.115226337448559,
 1.3717421124828528,
 0.4572473708276176,
 0.15241579027587254]

In [7]:
start_nbr = 100.0
vert_conc = [0.0]
for i in range(5):
    vert_conc.append(start_nbr)
    start_nbr /= 4.0

In [8]:
start_nbr = 50.0
vert_conc = [0.0]
for i in range(5):
    vert_conc.append(start_nbr)
    start_nbr /= 3.0

In [9]:
vert_conc

[0.0,
 50.0,
 16.666666666666668,
 5.555555555555556,
 1.851851851851852,
 0.617283950617284]

In [10]:
dfo

,2,3,4,5,6,7,8,9,10,11
0,479280,33900,83910,263530,491050,531310,579080,574590,521740,429980
1,68380,17140,20420,25360,33550,52890,56630,60620,49200,37980
2,161810,19410,30940,52950,124610,188660,212050,325810,154590,144730
3,380860,22970,46150,132940,317210,727110,508000,476700,399040,397120
4,497370,31090,86230,279370,763610,582590,608670,530260,588880,519750
5,670760,35850,131990,314220,648450,734670,634830,680710,612700,676520

In [11]:
# dfo.loc[:, 'vert_conc'] = vert_conc
dfo = dfo.assign(vert_conc=vert_conc)

In [12]:
dfo

,2,3,4,5,6,7,8,9,10,11,vert_conc
0,479280,33900,83910,263530,491050,531310,579080,574590,521740,429980,0.000000
1,68380,17140,20420,25360,33550,52890,56630,60620,49200,37980,50.000000
2,161810,19410,30940,52950,124610,188660,212050,325810,154590,144730,16.666667
3,380860,22970,46150,132940,317210,727110,508000,476700,399040,397120,5.555556
4,497370,31090,86230,279370,763610,582590,608670,530260,588880,519750,1.851852
5,670760,35850,131990,314220,648450,734670,634830,680710,612700,676520,0.617284

In [13]:
df = dfo.copy()

In [99]:
len(horiz_conc)

10

In [100]:
len(df.columns)

11

In [14]:
stubnames = [f'colval_{horiz_conc[i]}' for i in range(len(df.columns)-1)]
stubnames

['colval_0.0',
 'colval_1000.0',
 'colval_333.3333333333333',
 'colval_111.1111111111111',
 'colval_37.03703703703703',
 'colval_12.345679012345677',
 'colval_4.115226337448559',
 'colval_1.3717421124828528',
 'colval_0.4572473708276176',
 'colval_0.15241579027587254']

In [15]:
df.columns = stubnames + [df.columns[-1]]

In [16]:
df

,colval_0.0,colval_1000.0,colval_333.3333333333333,colval_111.1111111111111,colval_37.03703703703703,colval_12.345679012345677,colval_4.115226337448559,colval_1.3717421124828528,colval_0.4572473708276176,colval_0.15241579027587254,vert_conc
0,479280,33900,83910,263530,491050,531310,579080,574590,521740,429980,0.000000
1,68380,17140,20420,25360,33550,52890,56630,60620,49200,37980,50.000000
2,161810,19410,30940,52950,124610,188660,212050,325810,154590,144730,16.666667
3,380860,22970,46150,132940,317210,727110,508000,476700,399040,397120,5.555556
4,497370,31090,86230,279370,763610,582590,608670,530260,588880,519750,1.851852
5,670760,35850,131990,314220,648450,734670,634830,680710,612700,676520,0.617284

In [17]:
keys = [c for c in df if c.startswith('colval_')]
keys

['colval_0.0',
 'colval_1000.0',
 'colval_333.3333333333333',
 'colval_111.1111111111111',
 'colval_37.03703703703703',
 'colval_12.345679012345677',
 'colval_4.115226337448559',
 'colval_1.3717421124828528',
 'colval_0.4572473708276176',
 'colval_0.15241579027587254']

In [18]:
df_long = pd.melt(df, id_vars='vert_conc', value_vars=keys, value_name='effect')
df_long

    vert_conc                    variable  effect
0    0.000000                  colval_0.0  479280
1   50.000000                  colval_0.0   68380
2   16.666667                  colval_0.0  161810
3    5.555556                  colval_0.0  380860
4    1.851852                  colval_0.0  497370
5    0.617284                  colval_0.0  670760
6    0.000000               colval_1000.0   33900
7   50.000000               colval_1000.0   17140
8   16.666667               colval_1000.0   19410
9    5.555556               colval_1000.0   22970
10   1.851852               colval_1000.0   31090
11   0.617284               colval_1000.0   35850
12   0.000000    colval_333.3333333333333   83910
13  50.000000    colval_333.3333333333333   20420
14  16.666667    colval_333.3333333333333   30940
15   5.555556    colval_333.3333333333333   46150
16   1.851852    colval_333.3333333333333   86230
17   0.617284    colval_333.3333333333333  131990
18   0.000000    colval_111.1111111111111  263530
19  50.000000    colval_111.1111111111111   25360
20  16.666667    colval_111.1111111111111   52950
21   5.555556    colval_111.1111111111111  132940
22   1.851852    colval_111.1111111111111  279370
23   0.617284    colval_111.1111111111111  314220
24   0.000000    colval_37.03703703703703  491050
25  50.000000    colval_37.03703703703703   33550
26  16.666667    colval_37.03703703703703  124610
27   5.555556    colval_37.03703703703703  317210
28   1.851852    colval_37.03703703703703  763610
29   0.617284    colval_37.03703703703703  648450
30   0.000000   colval_12.345679012345677  531310
31  50.000000   colval_12.345679012345677   52890
32  16.666667   colval_12.345679012345677  188660
33   5.555556   colval_12.345679012345677  727110
34   1.851852   colval_12.345679012345677  582590
35   0.617284   colval_12.345679012345677  734670
36   0.000000    colval_4.115226337448559  579080
37  50.000000    colval_4.115226337448559   56630
38  16.666667    colval_4.115226337448559  212050
39   5.555556    colval_4.115226337448559  508000
40   1.851852    colval_4.115226337448559  608670
41   0.617284    colval_4.115226337448559  634830
42   0.000000   colval_1.3717421124828528  574590
43  50.000000   colval_1.3717421124828528   60620
44  16.666667   colval_1.3717421124828528  325810
45   5.555556   colval_1.3717421124828528  476700
46   1.851852   colval_1.3717421124828528  530260
47   0.617284   colval_1.3717421124828528  680710
48   0.000000   colval_0.4572473708276176  521740
49  50.000000   colval_0.4572473708276176   49200
50  16.666667   colval_0.4572473708276176  154590
51   5.555556   colval_0.4572473708276176  399040
52   1.851852   colval_0.4572473708276176  588880
53   0.617284   colval_0.4572473708276176  612700
54   0.000000  colval_0.15241579027587254  429980
55  50.000000  colval_0.15241579027587254   37980
56  16.666667  colval_0.15241579027587254  144730
57   5.555556  colval_0.15241579027587254  397120
58   1.851852  colval_0.15241579027587254  519750
59   0.617284  colval_0.15241579027587254  676520

In [19]:
df_long[['prefix','horiz_conc']] = df_long['variable'].str.split('_', expand=True)

In [20]:
df_long

    vert_conc                    variable  effect  prefix           horiz_conc
0    0.000000                  colval_0.0  479280  colval                  0.0
1   50.000000                  colval_0.0   68380  colval                  0.0
2   16.666667                  colval_0.0  161810  colval                  0.0
3    5.555556                  colval_0.0  380860  colval                  0.0
4    1.851852                  colval_0.0  497370  colval                  0.0
5    0.617284                  colval_0.0  670760  colval                  0.0
6    0.000000               colval_1000.0   33900  colval               1000.0
7   50.000000               colval_1000.0   17140  colval               1000.0
8   16.666667               colval_1000.0   19410  colval               1000.0
9    5.555556               colval_1000.0   22970  colval               1000.0
10   1.851852               colval_1000.0   31090  colval               1000.0
11   0.617284               colval_1000.0   35850  colval               1000.0
12   0.000000    colval_333.3333333333333   83910  colval    333.3333333333333
13  50.000000    colval_333.3333333333333   20420  colval    333.3333333333333
14  16.666667    colval_333.3333333333333   30940  colval    333.3333333333333
15   5.555556    colval_333.3333333333333   46150  colval    333.3333333333333
16   1.851852    colval_333.3333333333333   86230  colval    333.3333333333333
17   0.617284    colval_333.3333333333333  131990  colval    333.3333333333333
18   0.000000    colval_111.1111111111111  263530  colval    111.1111111111111
19  50.000000    colval_111.1111111111111   25360  colval    111.1111111111111
20  16.666667    colval_111.1111111111111   52950  colval    111.1111111111111
21   5.555556    colval_111.1111111111111  132940  colval    111.1111111111111
22   1.851852    colval_111.1111111111111  279370  colval    111.1111111111111
23   0.617284    colval_111.1111111111111  314220  colval    111.1111111111111
24   0.000000    colval_37.03703703703703  491050  colval    37.03703703703703
25  50.000000    colval_37.03703703703703   33550  colval    37.03703703703703
26  16.666667    colval_37.03703703703703  124610  colval    37.03703703703703
27   5.555556    colval_37.03703703703703  317210  colval    37.03703703703703
28   1.851852    colval_37.03703703703703  763610  colval    37.03703703703703
29   0.617284    colval_37.03703703703703  648450  colval    37.03703703703703
30   0.000000   colval_12.345679012345677  531310  colval   12.345679012345677
31  50.000000   colval_12.345679012345677   52890  colval   12.345679012345677
32  16.666667   colval_12.345679012345677  188660  colval   12.345679012345677
33   5.555556   colval_12.345679012345677  727110  colval   12.345679012345677
34   1.851852   colval_12.345679012345677  582590  colval   12.345679012345677
35   0.617284   colval_12.345679012345677  734670  colval   12.345679012345677
36   0.000000    colval_4.115226337448559  579080  colval    4.115226337448559
37  50.000000    colval_4.115226337448559   56630  colval    4.115226337448559
38  16.666667    colval_4.115226337448559  212050  colval    4.115226337448559
39   5.555556    colval_4.115226337448559  508000  colval    4.115226337448559
40   1.851852    colval_4.115226337448559  608670  colval    4.115226337448559
41   0.617284    colval_4.115226337448559  634830  colval    4.115226337448559
42   0.000000   colval_1.3717421124828528  574590  colval   1.3717421124828528
43  50.000000   colval_1.3717421124828528   60620  colval   1.3717421124828528
44  16.666667   colval_1.3717421124828528  325810  colval   1.3717421124828528
45   5.555556   colval_1.3717421124828528  476700  colval   1.3717421124828528
46   1.851852   colval_1.3717421124828528  530260  colval   1.3717421124828528
47   0.617284   colval_1.3717421124828528  680710  colval   1.3717421124828528
48   0.000000   colval_0.4572473708276176  521740  colval   0.4572473708276176
49  50.000000   colval_0.4572473708276176   49200  colval   0.4572473708276176
50  16.666667   colval_0.4572473708276176  154590  colval   0.4572473708276176
51   5.555556   colval_0.4572473708276176  399040  colval   0.4572473708276176
52   1.851852   colval_0.4572473708276176  588880  colval   0.4572473708276176
53   0.617284   colval_0.4572473708276176  612700  colval   0.4572473708276176
54   0.000000  colval_0.15241579027587254  429980  colval  0.15241579027587254
55  50.000000  colval_0.15241579027587254   37980  colval  0.15241579027587254
56  16.666667  colval_0.15241579027587254  144730  colval  0.15241579027587254
57   5.555556  colval_0.15241579027587254  397120  colval  0.15241579027587254
58   1.851852  colval_0.15241579027587254  519750  colval  0.15241579027587254
59   0.617284  colval_0.15241579027587254  676520  colval  0.15241579027587254

In [21]:
df_long = df_long.astype({'horiz_conc': 'float'})

In [105]:
df_long.dtypes

vert_conc     float64
variable       object
effect          int64
prefix         object
horiz_conc    float64
dtype: object

In [106]:
df_long

    vert_conc                    variable  effect  prefix   horiz_conc
0    0.000000                  colval_0.0  479280  colval     0.000000
1   50.000000                  colval_0.0   68380  colval     0.000000
2   16.666667                  colval_0.0  161810  colval     0.000000
3    5.555556                  colval_0.0  380860  colval     0.000000
4    1.851852                  colval_0.0  497370  colval     0.000000
5    0.617284                  colval_0.0  670760  colval     0.000000
6    0.000000               colval_1000.0   33900  colval  1000.000000
7   50.000000               colval_1000.0   17140  colval  1000.000000
8   16.666667               colval_1000.0   19410  colval  1000.000000
9    5.555556               colval_1000.0   22970  colval  1000.000000
10   1.851852               colval_1000.0   31090  colval  1000.000000
11   0.617284               colval_1000.0   35850  colval  1000.000000
12   0.000000    colval_333.3333333333333   83910  colval   333.333333
13  50.000000    colval_333.3333333333333   20420  colval   333.333333
14  16.666667    colval_333.3333333333333   30940  colval   333.333333
15   5.555556    colval_333.3333333333333   46150  colval   333.333333
16   1.851852    colval_333.3333333333333   86230  colval   333.333333
17   0.617284    colval_333.3333333333333  131990  colval   333.333333
18   0.000000    colval_111.1111111111111  263530  colval   111.111111
19  50.000000    colval_111.1111111111111   25360  colval   111.111111
20  16.666667    colval_111.1111111111111   52950  colval   111.111111
21   5.555556    colval_111.1111111111111  132940  colval   111.111111
22   1.851852    colval_111.1111111111111  279370  colval   111.111111
23   0.617284    colval_111.1111111111111  314220  colval   111.111111
24   0.000000    colval_37.03703703703703  491050  colval    37.037037
25  50.000000    colval_37.03703703703703   33550  colval    37.037037
26  16.666667    colval_37.03703703703703  124610  colval    37.037037
27   5.555556    colval_37.03703703703703  317210  colval    37.037037
28   1.851852    colval_37.03703703703703  763610  colval    37.037037
29   0.617284    colval_37.03703703703703  648450  colval    37.037037
30   0.000000   colval_12.345679012345677  531310  colval    12.345679
31  50.000000   colval_12.345679012345677   52890  colval    12.345679
32  16.666667   colval_12.345679012345677  188660  colval    12.345679
33   5.555556   colval_12.345679012345677  727110  colval    12.345679
34   1.851852   colval_12.345679012345677  582590  colval    12.345679
35   0.617284   colval_12.345679012345677  734670  colval    12.345679
36   0.000000    colval_4.115226337448559  579080  colval     4.115226
37  50.000000    colval_4.115226337448559   56630  colval     4.115226
38  16.666667    colval_4.115226337448559  212050  colval     4.115226
39   5.555556    colval_4.115226337448559  508000  colval     4.115226
40   1.851852    colval_4.115226337448559  608670  colval     4.115226
41   0.617284    colval_4.115226337448559  634830  colval     4.115226
42   0.000000   colval_1.3717421124828528  574590  colval     1.371742
43  50.000000   colval_1.3717421124828528   60620  colval     1.371742
44  16.666667   colval_1.3717421124828528  325810  colval     1.371742
45   5.555556   colval_1.3717421124828528  476700  colval     1.371742
46   1.851852   colval_1.3717421124828528  530260  colval     1.371742
47   0.617284   colval_1.3717421124828528  680710  colval     1.371742
48   0.000000   colval_0.4572473708276176  521740  colval     0.457247
49  50.000000   colval_0.4572473708276176   49200  colval     0.457247
50  16.666667   colval_0.4572473708276176  154590  colval     0.457247
51   5.555556   colval_0.4572473708276176  399040  colval     0.457247
52   1.851852   colval_0.4572473708276176  588880  colval     0.457247
53   0.617284   colval_0.4572473708276176  612700  colval     0.457247
54   0.000000  colval_0.15241579027587254  429980  colval     0.152416
55  50.000000  colval_0.15241579027587254   37980  colval     0.152416
56  16.666667  colval_0.15241579027587254  144730  colval     0.152416
57   5.555556  colval_0.15241579027587254  397120  colval     0.152416
58   1.851852  colval_0.15241579027587254  519750  colval     0.152416
59   0.617284  colval_0.15241579027587254  676520  colval     0.152416

In [70]:
dfm = df_long[["vert_conc", "horiz_conc", "effect"]]
dfm

    vert_conc   horiz_conc  effect
0    0.000000     0.000000  479280
1   50.000000     0.000000   68380
2   16.666667     0.000000  161810
3    5.555556     0.000000  380860
4    1.851852     0.000000  497370
5    0.617284     0.000000  670760
6    0.000000  1000.000000   33900
7   50.000000  1000.000000   17140
8   16.666667  1000.000000   19410
9    5.555556  1000.000000   22970
10   1.851852  1000.000000   31090
11   0.617284  1000.000000   35850
12   0.000000   333.333333   83910
13  50.000000   333.333333   20420
14  16.666667   333.333333   30940
15   5.555556   333.333333   46150
16   1.851852   333.333333   86230
17   0.617284   333.333333  131990
18   0.000000   111.111111  263530
19  50.000000   111.111111   25360
20  16.666667   111.111111   52950
21   5.555556   111.111111  132940
22   1.851852   111.111111  279370
23   0.617284   111.111111  314220
24   0.000000    37.037037  491050
25  50.000000    37.037037   33550
26  16.666667    37.037037  124610
27   5.555556    37.037037  317210
28   1.851852    37.037037  763610
29   0.617284    37.037037  648450
30   0.000000    12.345679  531310
31  50.000000    12.345679   52890
32  16.666667    12.345679  188660
33   5.555556    12.345679  727110
34   1.851852    12.345679  582590
35   0.617284    12.345679  734670
36   0.000000     4.115226  579080
37  50.000000     4.115226   56630
38  16.666667     4.115226  212050
39   5.555556     4.115226  508000
40   1.851852     4.115226  608670
41   0.617284     4.115226  634830
42   0.000000     1.371742  574590
43  50.000000     1.371742   60620
44  16.666667     1.371742  325810
45   5.555556     1.371742  476700
46   1.851852     1.371742  530260
47   0.617284     1.371742  680710
48   0.000000     0.457247  521740
49  50.000000     0.457247   49200
50  16.666667     0.457247  154590
51   5.555556     0.457247  399040
52   1.851852     0.457247  588880
53   0.617284     0.457247  612700
54   0.000000     0.152416  429980
55  50.000000     0.152416   37980
56  16.666667     0.152416  144730
57   5.555556     0.152416  397120
58   1.851852     0.152416  519750
59   0.617284     0.152416  676520

In [71]:
dfm = dfm.rename(columns={"vert_conc": "drug2.conc", "horiz_conc": "drug1.conc"})
dfm

    drug2.conc   drug1.conc  effect
0     0.000000     0.000000  479280
1    50.000000     0.000000   68380
2    16.666667     0.000000  161810
3     5.555556     0.000000  380860
4     1.851852     0.000000  497370
5     0.617284     0.000000  670760
6     0.000000  1000.000000   33900
7    50.000000  1000.000000   17140
8    16.666667  1000.000000   19410
9     5.555556  1000.000000   22970
10    1.851852  1000.000000   31090
11    0.617284  1000.000000   35850
12    0.000000   333.333333   83910
13   50.000000   333.333333   20420
14   16.666667   333.333333   30940
15    5.555556   333.333333   46150
16    1.851852   333.333333   86230
17    0.617284   333.333333  131990
18    0.000000   111.111111  263530
19   50.000000   111.111111   25360
20   16.666667   111.111111   52950
21    5.555556   111.111111  132940
22    1.851852   111.111111  279370
23    0.617284   111.111111  314220
24    0.000000    37.037037  491050
25   50.000000    37.037037   33550
26   16.666667    37.037037  124610
27    5.555556    37.037037  317210
28    1.851852    37.037037  763610
29    0.617284    37.037037  648450
30    0.000000    12.345679  531310
31   50.000000    12.345679   52890
32   16.666667    12.345679  188660
33    5.555556    12.345679  727110
34    1.851852    12.345679  582590
35    0.617284    12.345679  734670
36    0.000000     4.115226  579080
37   50.000000     4.115226   56630
38   16.666667     4.115226  212050
39    5.555556     4.115226  508000
40    1.851852     4.115226  608670
41    0.617284     4.115226  634830
42    0.000000     1.371742  574590
43   50.000000     1.371742   60620
44   16.666667     1.371742  325810
45    5.555556     1.371742  476700
46    1.851852     1.371742  530260
47    0.617284     1.371742  680710
48    0.000000     0.457247  521740
49   50.000000     0.457247   49200
50   16.666667     0.457247  154590
51    5.555556     0.457247  399040
52    1.851852     0.457247  588880
53    0.617284     0.457247  612700
54    0.000000     0.152416  429980
55   50.000000     0.152416   37980
56   16.666667     0.152416  144730
57    5.555556     0.152416  397120
58    1.851852     0.152416  519750
59    0.617284     0.152416  676520

In [32]:
vehicle_measurement = dfm['effect'][(dfm['drug1.conc'] == 0) & (dfm['drug2.conc'] == 0)].item()
vehicle_measurement

479280

In [33]:
highest_conc_measurement = dfm['effect'][(dfm['drug2.conc'] == max(vert_conc)) & (dfm['drug1.conc'] == max(horiz_conc))].item()
highest_conc_measurement

17140

In [41]:
highest_effect = max(dfm['effect'])
highest_effect

763610

In [54]:
lowest_effect = min(dfm['effect']) # highest inhibition
lowest_effect

17140

In [69]:
dfm.effect

0     1.037088
1     0.930411
2     1.128965
3     1.243325
4     0.073354
5     1.253040
6     1.149673
7     1.062557
8     0.181568
9     0.570238
10    1.325789
11    1.472952
12    1.373675
13    1.589713
14    0.679924
15    0.285606
16    1.403146
17    1.463885
18    1.451422
19    0.077574
20    1.317068
21    0.067274
22    1.124659
23    1.652335
24    0.186588
25    1.147401
26    0.604514
27    1.274246
28    1.076232
29    1.260635
30    1.031506
31    0.824123
32    0.863461
33    0.859307
34    1.099234
35    0.099862
36    1.573354
37    0.686394
38    0.287662
39    0.049704
40    0.042000
41    0.066949
42    0.313173
43    0.350132
44    0.114576
45    0.334509
46    0.458844
47    0.269637
48    0.705003
49    0.408231
50    0.106461
51    0.131172
52    0.037088
53    0.054875
54    0.114446
55    0.147964
56    0.082183
57    0.122539
58    0.072597
59    0.044186
Name: effect, dtype: float64

In [81]:
vert_conc

[0.0,
 50.0,
 16.666666666666668,
 5.555555555555556,
 1.851851851851852,
 0.617283950617284]

In [82]:
horiz_conc

[0.0,
 1000.0,
 333.3333333333333,
 111.1111111111111,
 37.03703703703703,
 12.345679012345677,
 4.115226337448559,
 1.3717421124828528,
 0.4572473708276176,
 0.15241579027587254]

In [77]:
# normalise on largest value and subtract by the blank
# DOES NOT WORK during fitting
dfm['effect'] =  dfm['effect'].apply(lambda eff: (eff)/(highest_effect))

In [64]:
# normalise on highest conc of both drugs subtracted from 
dfm['effect'] = dfm['effect'].apply(lambda eff: eff/(vehicle_measurement-highest_conc_measurement))

In [78]:
dfm.sort_values(by=["drug2.conc"], ignore_index=True, inplace=True)

In [79]:
dfm

    drug2.conc   drug1.conc    effect
0     0.000000     0.000000  0.627650
1     0.000000     0.152416  0.563088
2     0.000000     0.457247  0.683255
3     0.000000     1.371742  0.752465
4     0.000000  1000.000000  0.044394
5     0.000000     4.115226  0.758345
6     0.000000    12.345679  0.695787
7     0.000000    37.037037  0.643064
8     0.000000   333.333333  0.109886
9     0.000000   111.111111  0.345111
10    0.617284     0.457247  0.802373
11    0.617284     1.371742  0.891437
12    0.617284     4.115226  0.831354
13    0.617284    12.345679  0.962101
14    0.617284   111.111111  0.411493
15    0.617284   333.333333  0.172850
16    0.617284    37.037037  0.849190
17    0.617284     0.152416  0.885950
18    0.617284     0.000000  0.878407
19    0.617284  1000.000000  0.046948
20    1.851852     4.115226  0.797095
21    1.851852  1000.000000  0.040715
22    1.851852     0.152416  0.680648
23    1.851852    37.037037  1.000000
24    1.851852   333.333333  0.112924
25    1.851852     1.371742  0.694412
26    1.851852   111.111111  0.365854
27    1.851852     0.457247  0.771179
28    1.851852     0.000000  0.651340
29    1.851852    12.345679  0.762942
30    5.555556     1.371742  0.624272
31    5.555556     0.000000  0.498762
32    5.555556     0.457247  0.522570
33    5.555556     0.152416  0.520056
34    5.555556     4.115226  0.665261
35    5.555556   333.333333  0.060437
36    5.555556    12.345679  0.952201
37    5.555556    37.037037  0.415408
38    5.555556   111.111111  0.174094
39    5.555556  1000.000000  0.030081
40   16.666667  1000.000000  0.025419
41   16.666667   333.333333  0.040518
42   16.666667     0.152416  0.189534
43   16.666667     0.000000  0.211901
44   16.666667   111.111111  0.069342
45   16.666667     0.457247  0.202446
46   16.666667     4.115226  0.277694
47   16.666667    37.037037  0.163185
48   16.666667     1.371742  0.426671
49   16.666667    12.345679  0.247063
50   50.000000     0.457247  0.064431
51   50.000000     1.371742  0.079386
52   50.000000  1000.000000  0.022446
53   50.000000   111.111111  0.033211
54   50.000000    12.345679  0.069263
55   50.000000     0.000000  0.089548
56   50.000000     0.152416  0.049737
57   50.000000     4.115226  0.074161
58   50.000000    37.037037  0.043936
59   50.000000   333.333333  0.026741

In [115]:
dff = pd.read_csv("/home/jovyan/work/Downloads/OneDrive_1_3-22-2022/Skinny_IPC298.csv")

In [116]:
dfm = dfm.sort_values(by=['drug1.conc'], ignore_index=True)

In [134]:
pd.merge(dfm, dff, how="left", on=["drug1.conc", "drug2.conc"])

    drug2.conc   drug1.conc  effect_x  effect_y
0     0.000000     0.000000  1.037088  1.038098
1    50.000000     0.000000  0.147964  0.121277
2    16.666667     0.000000  0.350132       NaN
3     5.555556     0.000000  0.824123       NaN
4     1.851852     0.000000  1.076232       NaN
5     0.617284     0.000000  1.451422       NaN
6     0.000000  1000.000000  0.073354  0.078899
7    50.000000  1000.000000  0.037088  0.038098
8    16.666667  1000.000000  0.042000       NaN
9     5.555556  1000.000000  0.049704       NaN
10    1.851852  1000.000000  0.067274       NaN
11    0.617284  1000.000000  0.077574       NaN
12    0.000000   333.333333  0.181568       NaN
13   50.000000   333.333333  0.044186       NaN
14   16.666667   333.333333  0.066949       NaN
15    5.555556   333.333333  0.099862       NaN
16    1.851852   333.333333  0.186588       NaN
17    0.617284   333.333333  0.285606       NaN
18    0.000000   111.111111  0.570238       NaN
19   50.000000   111.111111  0.054875       NaN
20   16.666667   111.111111  0.114576       NaN
21    5.555556   111.111111  0.287662       NaN
22    1.851852   111.111111  0.604514       NaN
23    0.617284   111.111111  0.679924       NaN
24    0.000000    37.037037  1.062557       NaN
25   50.000000    37.037037  0.072597       NaN
26   16.666667    37.037037  0.269637       NaN
27    5.555556    37.037037  0.686394       NaN
28    1.851852    37.037037  1.652335       NaN
29    0.617284    37.037037  1.403146       NaN
30    0.000000    12.345679  1.149673       NaN
31   50.000000    12.345679  0.114446       NaN
32   16.666667    12.345679  0.408231       NaN
33    5.555556    12.345679  1.573354       NaN
34    1.851852    12.345679  1.260635       NaN
35    0.617284    12.345679  1.589713       NaN
36    0.000000     4.115226  1.253040       NaN
37   50.000000     4.115226  0.122539       NaN
38   16.666667     4.115226  0.458844       NaN
39    5.555556     4.115226  1.099234       NaN
40    1.851852     4.115226  1.317068       NaN
41    0.617284     4.115226  1.373675       NaN
42    0.000000     1.371742  1.243325       NaN
43   50.000000     1.371742  0.131172       NaN
44   16.666667     1.371742  0.705003       NaN
45    5.555556     1.371742  1.031506       NaN
46    1.851852     1.371742  1.147401       NaN
47    0.617284     1.371742  1.472952       NaN
48    0.000000     0.457247  1.128965       NaN
49   50.000000     0.457247  0.106461       NaN
50   16.666667     0.457247  0.334509       NaN
51    5.555556     0.457247  0.863461       NaN
52    1.851852     0.457247  1.274246       NaN
53    0.617284     0.457247  1.325789       NaN
54    0.000000     0.152416  0.930411       NaN
55   50.000000     0.152416  0.082183       NaN
56   16.666667     0.152416  0.313173       NaN
57    5.555556     0.152416  0.859307       NaN
58    1.851852     0.152416  1.124659       NaN
59    0.617284     0.152416  1.463885       NaN

In [132]:
dff.head()

   drug1.conc  drug2.conc    effect
0         0.0    0.000000  1.038098
1         0.0   50.000000  0.121277
2         0.0   16.666667  0.289203
3         0.0    5.555556  0.788677
4         0.0    1.851852  1.161231

In [48]:
df.head()

,colval_0.0,colval_1000.0,colval_333.3333333333333,colval_111.1111111111111,colval_37.03703703703703,colval_12.345679012345677,colval_4.115226337448559,colval_1.3717421124828528,colval_0.4572473708276176,colval_0.15241579027587254,vert_conc
0,479280,33900,83910,263530,491050,531310,579080,574590,521740,429980,0.000000
1,68380,17140,20420,25360,33550,52890,56630,60620,49200,37980,50.000000
2,161810,19410,30940,52950,124610,188660,212050,325810,154590,144730,16.666667
3,380860,22970,46150,132940,317210,727110,508000,476700,399040,397120,5.555556
4,497370,31090,86230,279370,763610,582590,608670,530260,588880,519750,1.851852

In [136]:
dff['drug1.conc'].unique().tolist()

[0.0,
 1000.0,
 333.3333333,
 111.1111111,
 37.03703704,
 12.34567901,
 4.115226337,
 1.371742112,
 0.457247371,
 0.15241579]

In [140]:
def f(x):
    return round(x,2)

In [142]:
list(map(f, dfm['drug1.conc'].unique().tolist()))

[0.0, 1000.0, 333.33, 111.11, 37.04, 12.35, 4.12, 1.37, 0.46, 0.15]

In [137]:
dfm['drug1.conc'].unique().tolist() ==dff['drug1.conc'].unique().tolist()

False

In [154]:
dfa = dfm.copy()
dfb = dff.copy()
dfa[['drug1.conc', 'drug2.conc']] = dfa[['drug1.conc', 'drug2.conc']].apply(f)
dfb[['drug1.conc', 'drug2.conc']] = dfb[['drug1.conc', 'drug2.conc']].apply(f)

In [155]:
pd.merge(dfa, dfb, how="left", on=["drug1.conc", "drug2.conc"])

    drug2.conc  drug1.conc  effect_x  effect_y
0         0.00        0.00  1.037088  1.038098
1        50.00        0.00  0.147964  0.121277
2        16.67        0.00  0.350132  0.289203
3         5.56        0.00  0.824123  0.788677
4         1.85        0.00  1.076232  1.161231
5         0.62        0.00  1.451422  1.430038
6         0.00     1000.00  0.073354  0.078899
7        50.00     1000.00  0.037088  0.038098
8        16.67     1000.00  0.042000  0.044803
9         5.56     1000.00  0.049704  0.052753
10        1.85     1000.00  0.067274  0.070670
11        0.62     1000.00  0.077574  0.073631
12        0.00      333.33  0.181568  0.188428
13       50.00      333.33  0.044186  0.043526
14       16.67      333.33  0.066949  0.065198
15        5.56      333.33  0.099862  0.096129
16        1.85      333.33  0.186588  0.175822
17        0.62      333.33  0.285606  0.234637
18        0.00      111.11  0.570238  0.574296
19       50.00      111.11  0.054875  0.057495
20       16.67      111.11  0.114576  0.120161
21        5.56      111.11  0.287662  0.281778
22        1.85      111.11  0.604514  0.632424
23        0.62      111.11  0.679924  0.650041
24        0.00       37.04  1.062557  1.088662
25       50.00       37.04  0.072597  0.077139
26       16.67       37.04  0.269637  0.246513
27        5.56       37.04  0.686394  0.767949
28        1.85       37.04  1.652335  1.489797
29        0.62       37.04  1.403146  1.364818
30        0.00       12.35  1.149673  1.197365
31       50.00       12.35  0.114446  0.109540
32       16.67       12.35  0.408231  0.365977
33        5.56       12.35  1.573354  1.294782
34        1.85       12.35  1.260635  1.337289
35        0.62       12.35  1.589713  1.587160
36        0.00        4.12  1.253040  1.261115
37       50.00        4.12  0.122539  0.120751
38       16.67        4.12  0.458844  0.468361
39        5.56        4.12  1.099234  1.107180
40        1.85        4.12  1.317068  1.349830
41        0.62        4.12  1.373675  1.549513
42        0.00        1.37  1.243325  1.236214
43       50.00        1.37  0.131172  0.133089
44       16.67        1.37  0.705003  0.563396
45        5.56        1.37  1.031506  1.087632
46        1.85        1.37  1.147401  1.223586
47        0.62        1.37  1.472952  1.522026
48        0.00        0.46  1.128965  1.109057
49       50.00        0.46  0.106461  0.107759
50       16.67        0.46  0.334509  0.329628
51        5.56        0.46  0.863461  0.903774
52        1.85        0.46  1.274246  1.274494
53        0.62        0.46  1.325789  1.392359
54        0.00        0.15  0.930411  1.012649
55       50.00        0.15  0.082183  0.088276
56       16.67        0.15  0.313173  0.363703
57        5.56        0.15  0.859307  0.965142
58        1.85        0.15  1.124659  1.159225
59        0.62        0.15  1.463885  1.537593

In [175]:
#norm_mean = (dfm['effect']-dfm['effect'].mean())/dfm['effect'].std()

In [176]:
# norm_mean_df = dfm[["drug1.conc", "drug2.conc"]] 
# norm_mean_df["effect"] = norm_mean

In [178]:
# norm_minmax = (dfm['effect']-dfm['effect'].min())/(dfm['effect'].max()-dfm['effect'].min())

In [179]:
# norm_minmax_df = dfm[["drug1.conc", "drug2.conc"]] 
# norm_minmax_df["effect"] = norm_minmax

In [46]:
dfm.to_json("/home/jovyan/work/Documents/pythonScripts/fastapi-apps/test-musyc/backend/combo-data.json")

In [156]:
dfm.to_json("/home/jovyan/work/Documents/gitrepos/musyc/backend/combo-data.json")

In [80]:
dfm.to_csv("data.csv")

In [50]:
pd.read_json("/home/jovyan/work/Documents/gitrepos/musyc/backend/combo-data.json")

    drug1.conc   drug2.conc    effect
0     0.000000     0.000000  1.015124
1   100.000000     0.000000  0.121811
2    25.000000     0.000000  0.628006
3     6.250000     0.000000  1.113496
4     1.562500     0.000000  1.235222
5     0.390625     0.000000  1.181391
6     0.000000  1000.000000  0.049767
7   100.000000  1000.000000  0.015124
8    25.000000  1000.000000  0.028177
9     6.250000  1000.000000  0.040694
10    1.562500  1000.000000  0.050110
11    0.390625  1000.000000  0.054770
12    0.000000   333.333333  0.150824
13  100.000000   333.333333  0.021789
14   25.000000   333.333333  0.042813
15    6.250000   333.333333  0.081273
16    1.562500   333.333333  0.138373
17    0.390625   333.333333  0.153600
18    0.000000   111.111111  0.621786
19  100.000000   111.111111  0.030736
20   25.000000   111.111111  0.079931
21    6.250000   111.111111  0.201916
22    1.562500   111.111111  0.467561
23    0.390625   111.111111  0.640360
24    0.000000    37.037037  0.992107
25  100.000000    37.037037  0.042422
26   25.000000    37.037037  0.160542
27    6.250000    37.037037  0.696377
28    1.562500    37.037037  1.036311
29    0.390625    37.037037  1.159717
30    0.000000    12.345679  1.075523
31  100.000000    12.345679  0.071718
32   25.000000    12.345679  0.382103
33    6.250000    12.345679  1.118933
34    1.562500    12.345679  1.257637
35    0.390625    12.345679  1.347105
36    0.000000     4.115226  1.060755
37  100.000000     4.115226  0.124490
38   25.000000     4.115226  0.689519
39    6.250000     4.115226  1.173161
40    1.562500     4.115226  1.286248
41    0.390625     4.115226  1.302329
42    0.000000     1.371742  1.005750
43  100.000000     1.371742  0.197165
44   25.000000     1.371742  0.839181
45    6.250000     1.371742  1.198352
46    1.562500     1.371742  1.272003
47    0.390625     1.371742  1.309289
48    0.000000     0.457247  1.054541
49  100.000000     0.457247  0.176292
50   25.000000     0.457247  0.852909
51    6.250000     0.457247  1.180946
52    1.562500     0.457247  1.284893
53    0.390625     0.457247  1.317423
54    0.000000     0.152416  0.999976
55  100.000000     0.152416  0.161342
56   25.000000     0.152416  0.739828
57    6.250000     0.152416  1.164323
58    1.562500     0.152416  1.275242
59    0.390625     0.152416  1.323847

In [47]:
pd.read_json("/home/jovyan/work/Documents/pythonScripts/fastapi-apps/test-musyc/backend/combo-data.json")

    drug1.conc   drug2.conc    effect
0     0.000000     0.000000  1.015124
1   100.000000     0.000000  0.121811
2    25.000000     0.000000  0.628006
3     6.250000     0.000000  1.113496
4     1.562500     0.000000  1.235222
5     0.390625     0.000000  1.181391
6     0.000000  1000.000000  0.049767
7   100.000000  1000.000000  0.015124
8    25.000000  1000.000000  0.028177
9     6.250000  1000.000000  0.040694
10    1.562500  1000.000000  0.050110
11    0.390625  1000.000000  0.054770
12    0.000000   333.333333  0.150824
13  100.000000   333.333333  0.021789
14   25.000000   333.333333  0.042813
15    6.250000   333.333333  0.081273
16    1.562500   333.333333  0.138373
17    0.390625   333.333333  0.153600
18    0.000000   111.111111  0.621786
19  100.000000   111.111111  0.030736
20   25.000000   111.111111  0.079931
21    6.250000   111.111111  0.201916
22    1.562500   111.111111  0.467561
23    0.390625   111.111111  0.640360
24    0.000000    37.037037  0.992107
25  100.000000    37.037037  0.042422
26   25.000000    37.037037  0.160542
27    6.250000    37.037037  0.696377
28    1.562500    37.037037  1.036311
29    0.390625    37.037037  1.159717
30    0.000000    12.345679  1.075523
31  100.000000    12.345679  0.071718
32   25.000000    12.345679  0.382103
33    6.250000    12.345679  1.118933
34    1.562500    12.345679  1.257637
35    0.390625    12.345679  1.347105
36    0.000000     4.115226  1.060755
37  100.000000     4.115226  0.124490
38   25.000000     4.115226  0.689519
39    6.250000     4.115226  1.173161
40    1.562500     4.115226  1.286248
41    0.390625     4.115226  1.302329
42    0.000000     1.371742  1.005750
43  100.000000     1.371742  0.197165
44   25.000000     1.371742  0.839181
45    6.250000     1.371742  1.198352
46    1.562500     1.371742  1.272003
47    0.390625     1.371742  1.309289
48    0.000000     0.457247  1.054541
49  100.000000     0.457247  0.176292
50   25.000000     0.457247  0.852909
51    6.250000     0.457247  1.180946
52    1.562500     0.457247  1.284893
53    0.390625     0.457247  1.317423
54    0.000000     0.152416  0.999976
55  100.000000     0.152416  0.161342
56   25.000000     0.152416  0.739828
57    6.250000     0.152416  1.164323
58    1.562500     0.152416  1.275242
59    0.390625     0.152416  1.323847

In [183]:
pd.read_csv("https://raw.githubusercontent.com/djwooten/synergy/master/datasets/sample_data_1.csv")

    drug1.conc  drug2.conc    effect
0        0.000       0.000  1.004881
1        0.025       0.000  1.020909
2        0.050       0.000  1.000818
3        0.100       0.000  0.883694
4        0.200       0.000  0.513160
5        0.400       0.000  0.424048
6        0.800       0.000  0.394369
7        0.000       0.025  0.980774
8        0.025       0.025  0.984856
9        0.050       0.025  0.889224
10       0.100       0.025  0.674907
11       0.200       0.025  0.412910
12       0.400       0.025  0.396022
13       0.800       0.025  0.441060
14       0.000       0.050  0.822800
15       0.025       0.050  0.818847
16       0.050       0.050  0.750292
17       0.100       0.050  0.556546
18       0.200       0.050  0.409630
19       0.400       0.050  0.413634
20       0.800       0.050  0.443309
21       0.000       0.100  0.762226
22       0.025       0.100  0.720685
23       0.050       0.100  0.675776
24       0.100       0.100  0.394454
25       0.200       0.100  0.379349
26       0.400       0.100  0.329224
27       0.800       0.100  0.432025
28       0.000       0.200  0.569874
29       0.025       0.200  0.551215
30       0.050       0.200  0.465943
31       0.100       0.200  0.375250
32       0.200       0.200  0.310242
33       0.400       0.200  0.320641
34       0.800       0.200  0.279838
35       0.000       0.400  0.446067
36       0.025       0.400  0.433598
37       0.050       0.400  0.329450
38       0.100       0.400  0.154925
39       0.200       0.400  0.080548
40       0.400       0.400  0.044271
41       0.800       0.400  0.051993
42       0.000       0.800  0.378167
43       0.025       0.800  0.302265
44       0.050       0.800  0.258754
45       0.100       0.800  0.065664
46       0.200       0.800  0.023114
47       0.400       0.800  0.034843
48       0.800       0.800  0.016457